base_dir: data
batch_size: 32
data_path: null
device: null
force_reload: false
k_neighbors: 8
learning_rate: 0.001
max_samples: 5000
model_config: null
num_classes: 8
num_workers: null
projection_dim: 128
return_tensor: true
survey: gaia
task_type: classification
temperature: 0.1
train_ratio: 0.7
training_config: null
val_ratio: 0.15
weight_decay: 0.0001
