model:
  type: gaia_classifier
  params:
    hidden_dim: 256
    num_classes: 7 # Main sequence, Giants, White dwarfs, etc.
    dropout: 0.1
    use_batch_norm: true

data:
  dataset: gaia
  data_dir: data/processed
  cache_dir: data/cache
  batch_size: 64
  num_workers: 4
  sample_size: 50000
  split_ratios: [0.7, 0.15, 0.15] # train, val, test
  augmentation:
    noise_std: 0.01
    magnitude_shift: 0.1

training:
  task_type: classification
  experiment_name: gaia_stellar_classification_v2
  max_epochs: 150
  patience: 15
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: cosine
  warmup_epochs: 10
  accelerator: auto
  devices: auto
  precision: 16-mixed
  gradient_clip_val: 1.0

  # Loss function parameters
  loss_params:
    label_smoothing: 0.1
    class_weights: auto # Compute from data

optimization:
  n_trials: 100
  timeout: 7200 # 2 hours
  study_name: gaia_classification_optimization
  direction: maximize # maximize validation accuracy

  # Parameter search space
  search_space:
    learning_rate:
      type: loguniform
      low: 1e-5
      high: 1e-2
    hidden_dim:
      type: categorical
      choices: [128, 256, 512, 1024]
    dropout:
      type: uniform
      low: 0.0
      high: 0.3
    weight_decay:
      type: loguniform
      low: 1e-6
      high: 1e-3

# MLflow configuration
mlflow:
  tracking_uri: file:./data/experiments
  experiment_description: "Gaia DR3 stellar classification using photometry and astrometry"
  tags:
    survey: Gaia
    task: stellar_classification
    data_release: DR3
    version: v2.0

# Callbacks and monitoring
callbacks:
  early_stopping:
    monitor: val_accuracy
    patience: 15
    min_delta: 0.001
    mode: max

  model_checkpoint:
    monitor: val_accuracy
    save_top_k: 3
    mode: max
    save_last: true

  lr_monitor:
    logging_interval: epoch
