# Modern AstroLab Preprocessing Configuration
# =========================================

# Train/Validation/Test Split Configuration
split_config:
  test_size: 0.2 # 20% for test set
  val_size: 0.1 # 10% for validation set (70% for training)
  random_state: 42 # For reproducible results
  shuffle: true # Mix data before split

# Data Preprocessing Options
preprocessing:
  clean_null_columns: true # Remove columns with >95% null values
  min_observations_factor: 1.0 # Multiplier for minimum observations

# Parallel Processing Configuration
parallel_processing:
  n_threads: null # null = use all available threads

# Dataset-specific Overrides (optional)
dataset_overrides:
  nsa:
    split_config:
      stratify_column: null # No stratification for NSA

  exoplanet:
    split_config:
      stratify_column: "disposition" # Stratify by exoplanet status
    preprocessing:
      min_observations_factor: 0.8 # Less strict filtering

  linear_lightcurves:
    split_config:
      stratify_column: "classification"
    preprocessing:
      min_observations_factor: 1.5 # Stricter filtering for lightcurves

  rrlyrae:
    preprocessing:
      min_observations_factor: 2.0 # Very strict filtering for RR Lyrae

# Advanced Options
advanced:
  cache_intermediate: true # Cache intermediate results
  validate_splits: true # Check splits for consistency
  create_backup: false # Create backup of old splits

# Output Configuration
output:
  save_metadata: true # Create metadata YAML files
  save_statistics: true # Save data statistics
  compression_level: 6 # Parquet compression (0-9)

# Logging Configuration
logging:
  level: "INFO" # DEBUG, INFO, WARNING, ERROR
  show_progress: true # Show progress bars
  log_to_file: false # Write log to file
