model:
  type: gaia_classifier
  params:
    hidden_dim: 64 # Reduced to match smaller input features
    num_classes: 8
    dropout: 0.1
    num_layers: 2 # Reduced complexity for smaller dataset
    conv_type: "gcn" # Simpler than GAT for initial testing

data:
  dataset: exoplanets
  batch_size: 32 # Increased for better logging stability
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  train_val_test_split: [0.7, 0.15, 0.15]
  random_seed: 42
  augment_on_load: false

  # Dataset-specific parameters
  k_neighbors: 5
  max_distance: 100.0
  node_batch_size: 256 # Larger node batches for fewer total batches

training:
  task_type: unsupervised
  experiment_name: exoplanet_fixed_features
  max_epochs: 50 # Reduced for faster testing
  patience: 10
  learning_rate: 0.001
  weight_decay: 0.0001
  scheduler: cosine
  precision: 16-mixed
  gradient_clip_val: 1.0
  accumulate_grad_batches: 1
  enable_swa: false # Disabled for initial testing
  run_test: false
  log_every_n_steps: 1 # Log every step for small datasets

optimization:
  n_trials: 10 # Reduced for faster testing
  timeout: 1800 # 30 minutes
