model:
  type: gaia_classifier
  params:
    hidden_dim: 256
    num_classes: 10 # Universal astronomical representation
    dropout: 0.1

data:
  # Multi-dataset training would require special handling
  # For now, we'll use one primary dataset
  dataset: gaia
  batch_size: 32
  num_workers: 4
  magnitude_limit: 16.0
  k_neighbors: 8
  max_distance: 2.0
  shuffle: true

training:
  task_type: unsupervised
  experiment_name: multi_survey_universal_representation
  max_epochs: 150
  patience: 20
  learning_rate: 0.0008
  weight_decay: 0.0002
  scheduler: cosine
  accelerator: auto
  devices: auto
  precision: 16-mixed

optimization:
  n_trials: 50
  timeout: 7200 # 2 hours
