model:
  type: gaia_classifier
  params:
    hidden_dim: 96
    num_classes: 6 # Orbital elements
    dropout: 0.2

data:
  dataset: satellites
  batch_size: 16
  num_workers: 2
  max_satellites: 200
  k_neighbors: 8
  orbital_similarity_threshold: 2000.0 # km
  shuffle: true

training:
  task_type: unsupervised
  experiment_name: satellite_orbital_dynamics
  max_epochs: 100
  patience: 20
  learning_rate: 0.001
  weight_decay: 0.0005
  scheduler: cosine
  accelerator: auto
  devices: auto
  precision: 16-mixed

optimization:
  n_trials: 30
  timeout: 3600
