data:
  batch_size: 32
  dataset: gaia
  k_neighbors: 8
  magnitude_limit: 15.0
  num_workers: 4
  sample_size: 10000
  shuffle: true
model:
  params:
    dropout: 0.1
    hidden_dim: 128
    num_classes: 7
  type: gaia_classifier
optimization:
  n_trials: 50
  timeout: 3600
training:
  accelerator: auto
  devices: auto
  experiment_name: gaia_stellar_classification
  learning_rate: 0.001
  max_epochs: 100
  patience: 10
  precision: 16-mixed
  scheduler: cosine
  task_type: classification
  weight_decay: 0.0001
