data:
  batch_size: 32
  dataset: gaia
  max_samples: 1000
mlflow:
  experiment_name: quick_gaia_classifier_gaia
  tracking_uri: ./mlruns
model:
  params:
    dropout: 0.2
    hidden_dim: 128
    num_layers: 3
  type: gaia_classifier
training:
  learning_rate: 0.001
  max_epochs: 100
  patience: 5
  weight_decay: 0.0001
