data:
  batch_size: 16
  dataset: nsa # Wir haben NSA-Daten
  num_workers: 2
  sample_size: 1000 # Sehr klein für schnellen Test
  shuffle: true

model:
  params:
    dropout: 0.1
    hidden_dim: 32 # Sehr klein
    num_classes: 3 # Vereinfacht
  type: sdss_galaxy_classifier

optimization:
  n_trials: 2 # Nur 2 trials für schnellen Test
  timeout: 120 # 2 Minuten

training:
  accelerator: auto
  devices: auto
  experiment_name: small_model_test
  learning_rate: 0.001
  max_epochs: 2 # Nur 2 Epochen für schnellen Test
  patience: 2
  precision: 32 # Keine mixed precision für Kompatibilität
  scheduler: cosine
  task_type: classification
  weight_decay: 0.0001
