batch_size: 1
data_root: null
drop_last: true
ema_decay: 0.999
gradient_accumulation_steps: 1
gradient_clip_algorithm: norm
gradient_clip_val: 1.0
k_neighbors: 8
label_smoothing: 0.0
learning_rate: 0.001
max_nodes_per_graph: 1000
max_samples: 100
model_config: &id001 !!python/object:astro_lab.models.config.ModelConfig
  activation: relu
  conv_type: gcn
  dropout: 0.1
  hidden_dim: 32
  name: test_gnn
  num_heads: 8
  num_layers: 2
  output_dim: 8
  pooling: mean
  task: classification
  use_astrometry: true
  use_photometry: true
  use_spectroscopy: false
num_classes: null
num_workers: null
persistent_workers: true
pin_memory: true
prefetch_factor: 2
projection_dim: 128
scheduler_type: cosine
survey: gaia
task_type: classification
temperature: 0.1
train_ratio: 0.6
training_config: !!python/object:astro_lab.training.config.TrainingConfig
  __dict__:
    callbacks: !!python/object:astro_lab.training.config.CallbackConfig
      __dict__:
        custom_callbacks: []
        early_stopping: true
        early_stopping_mode: min
        early_stopping_monitor: val_loss
        early_stopping_patience: 15
        lr_monitor: true
        lr_monitor_logging_interval: epoch
        mode: min
        model_checkpoint: true
        monitor: val_loss
        rich_progress: true
        save_top_k: 3
        swa: false
        swa_epoch_start: 0.8
        swa_lrs: null
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set {}
      __pydantic_private__: null
    data: !!python/object:astro_lab.training.config.DataConfig
      __dict__:
        augmentation_config: {}
        batch_size: 32
        cache_dir: null
        data_dir: null
        num_workers: 4
        persistent_workers: true
        pin_memory: true
        test_split: 0.1
        use_augmentation: false
        val_split: 0.2
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set {}
      __pydantic_private__: null
    description: null
    hardware: !!python/object:astro_lab.training.config.HardwareConfig
      __dict__:
        accelerator: cpu
        accumulate_grad_batches: 1
        deterministic: false
        devices: 1
        enable_checkpointing: true
        enable_model_summary: true
        enable_progress_bar: true
        gradient_clip_val: 1.0
        num_sanity_val_steps: 0
        precision: 16-mixed
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        accelerator: null
        devices: null
      __pydantic_private__: null
    logging: !!python/object:astro_lab.training.config.LoggingConfig
      __dict__:
        custom_loggers: []
        experiment_name: astro_experiment
        log_every_n_steps: 1
        log_metrics:
        - train_loss
        - val_loss
        - train_acc
        - val_acc
        - learning_rate
        run_name: null
        tracking_uri: null
        use_mlflow: true
        val_check_interval: 1.0
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set {}
      __pydantic_private__: null
    model: *id001
    name: test_training
    scheduler: !!python/object:astro_lab.training.config.SchedulerConfig
      __dict__:
        decay_rate: 0.95
        div_factor: 25.0
        eta_min: 1.0e-06
        factor: 0.5
        final_div_factor: 10000.0
        gamma: 0.1
        learning_rate: 0.001
        max_epochs: 1
        min_lr: 1.0e-06
        patience: 10
        scheduler_type: cosine
        step_size: 30
        warmup_epochs: 5
        weight_decay: 0.0001
      __pydantic_extra__: null
      __pydantic_fields_set__: !!set
        max_epochs: null
      __pydantic_private__: null
    survey_overrides: {}
    training: null
    version: 1.0.0
  __pydantic_extra__: null
  __pydantic_fields_set__: !!set
    hardware: null
    model: null
    name: null
    scheduler: null
  __pydantic_private__: null
use_compile: true
use_distributed_sampler: true
use_ema: false
use_subgraph_sampling: true
val_ratio: 0.2
warmup_steps: 0
weight_decay: 0.0001
