name: "NASA-Sloan Atlas"
description: "NASA-Sloan Atlas (NSA) catalog with ~640,000 galaxies up to z < 0.15"
version: "v1_0_1"
file_format: "fits"
url: "http://nsatlas.org"

# Primary features from NSA catalog
features:
  # Basic properties
  - "RA" # Right Ascension (J2000)
  - "DEC" # Declination (J2000)
  - "Z" # Heliocentric redshift
  - "ZDIST" # Distance estimate (redshift equivalent)
  - "MAG" # Nominal B magnitude

  # Elliptical Petrosian photometry (recommended)
  - "ELPETRO_FLUX" # Elliptical Petrosian flux in FNugriz
  - "ELPETRO_ABSMAG" # Absolute magnitudes in FNugriz
  - "ELPETRO_MASS" # Stellar mass
  - "ELPETRO_TH50" # 50% light radius
  - "ELPETRO_TH90" # 90% light radius
  - "ELPETRO_BA" # Axis ratio b/a
  - "ELPETRO_PHI" # Position angle

  # Sersic profile fits
  - "SERSIC_FLUX" # Sersic fit flux
  - "SERSIC_ABSMAG" # Sersic absolute magnitudes
  - "SERSIC_MASS" # Sersic stellar mass
  - "SERSIC_N" # Sersic index
  - "SERSIC_BA" # Sersic axis ratio
  - "SERSIC_PHI" # Sersic position angle
  - "SERSIC_TH50" # Sersic 50% light radius

  # Additional properties
  - "ASYMMETRY" # Asymmetry parameter
  - "CLUMPY" # Clumpiness parameter
  - "EXTINCTION" # Galactic extinction

# Graph construction parameters
graph:
  k_neighbors: 10
  distance_metric: "euclidean"
  coordinate_features: ["RA", "DEC", "Z"] # Include redshift for 3D

# Tensor configuration for astro_lab tensors
tensor_config:
  spatial:
    coordinate_system: "icrs"
    unit: "Mpc"
    use_redshift_distance: true
  photometric:
    bands: ["F", "N", "u", "g", "r", "i", "z"] # GALEX + SDSS
    magnitude_system: "AB"
  survey:
    survey_name: "nsa"
    data_release: "v1_0_1"
    filter_system: "galex_sdss"

# Processing configuration
processing:
  normalize_features: true
  handle_missing: "drop"
  coordinate_system: "equatorial"

# Data splits
splits:
  train: 0.7
  val: 0.15
  test: 0.15

# Quality filters
filters:
  redshift_range: [0.0, 0.15] # z < 0.15 as per NSA selection
  magnitude_range: [10.0, 25.0] # Reasonable magnitude range
