# SDSS Survey Configuration
# =========================

survey:
  name: sdss
  description: "Sloan Digital Sky Survey - Photometric and spectroscopic data"

  # Features to use for ML models
  features:
    - ra # Right ascension
    - dec # Declination
    - modelMag_u # u-band magnitude
    - modelMag_g # g-band magnitude
    - modelMag_r # r-band magnitude
    - modelMag_i # i-band magnitude
    - modelMag_z # z-band magnitude
    - z # Redshift

  # Graph construction parameters
  graph:
    k_neighbors: 8 # Number of nearest neighbors
    distance_metric: euclidean

  # Data processing
  processing:
    normalize_features: true
    remove_outliers: true
    outlier_threshold: 3.0 # sigma threshold
