# Realistic Gaia Stellar Classification Training
# =============================================
# Stable configuration with 2025 optimizations

# Model Configuration
model:
  type: gaia_classifier
  params:
    input_dim: 16 # Standard Gaia features
    hidden_dim: 128 # Good balance
    output_dim: 4 # Astronomical classification: Main_Sequence, Red_Giant, White_Dwarf, Binary_System
    num_layers: 3
    dropout: 0.2 # Reasonable dropout
    use_batch_norm: true
    conv_type: "gcn" # Stable GCN layers
    activation: "relu"
    pooling: "mean"

# Data Configuration
data:
  dataset: gaia
  data_dir: data/processed
  batch_size: 64 # Larger batch for stability
  max_samples: null # Use all available samples
  k_neighbors: 8

  # Data loading optimizations (2025)
  num_workers: 4
  pin_memory: true
  persistent_workers: true
  prefetch_factor: 2
  return_tensor: true
  split_ratios: [0.7, 0.15, 0.15] # Standard splits

  # Data preprocessing for stability
  normalize: true
  standardize: true

# Training Configuration
training:
  # Basic settings
  max_epochs: 20
  learning_rate: 0.0001 # Conservative for large datasets
  weight_decay: 0.0001

  #  optimization (2025)
  gradient_accumulation_steps: 1
  gradient_clip_val: 0.5 # Stricter clipping for stability
  gradient_clip_algorithm: "norm"

  # Learning rate scheduler
  scheduler_type: "cosine" # More stable than step
  warmup_steps: 100 # Warmup for stability

  # Mixed precision (2025)
  precision: "16-mixed" # Enable when stable
  use_compile: false # Disable initially for debugging

  # Model EMA for better generalization
  use_ema: true
  ema_decay: 0.999

  # Regularization
  label_smoothing: 0.1 # Helps with overfitting

  # Callbacks
  patience: 5 # Early stopping patience
  use_swa: false # Enable later if needed

  # Hardware settings
  devices: auto
  strategy: auto # Will use DDP if multiple GPUs

  # Performance tuning
  deterministic: true # For reproducibility
  benchmark: false # For consistent timing
  profiler: null # Enable for performance analysis

# MLflow Configuration
mlflow:
  tracking_uri: ./mlruns
  experiment_name: gaia_realistic_training_2025
  experiment_description: "Stable Gaia stellar classification with 2025 optimizations"

  tags:
    survey: Gaia
    task: stellar_classification
    version: v2.0
    stable: true
    year: 2025

#  Features
advanced:
  # Gradient monitoring to catch problems early
  log_gradient_norm: true
  gradient_log_interval: 10

  # Model validation
  check_finite_gradients: true
  check_finite_losses: true
  log_nan_warnings: true

  # Memory optimization
  empty_cache_freq: 100

  # Logging
  log_every_n_steps: 50
  val_check_interval: 1.0

# Validation and metrics
validation:
  metrics:
    - "accuracy"
    - "f1_score"
    - "precision"
    - "recall"
    - "confusion_matrix"

# Reproducibility
seed: 42

# Production readiness
production:
  save_onnx: false # Export to ONNX when ready
  optimize_for_inference: false
  quantize: false # 8-bit quantization for deployment
