# Gaia Stellar Classification - OPTIMIZED with Optuna Results
# ===========================================================

model:
  type: gaia_classifier
  params:
    hidden_dim: 384 # Optimized from 64 → 384
    num_classes: 8
    dropout: 0.145 # Optimized from 0.10 → 0.145
    num_layers: 2 # Optimized
    use_batch_norm: true

data:
  dataset: gaia
  data_dir: data/processed
  batch_size: 32 # Smaller batch size for testing
  num_workers: 2 # Reduced for testing
  persistent_workers: false # Disabled for testing
  max_samples: 5000 # Larger dataset for optimized training
  return_tensor: true
  split_ratios: [0.8, 0.1, 0.1]

  # Data augmentation and preprocessing
  normalize: true
  standardize: true

training:
  max_epochs: 30 # More epochs for optimized model
  learning_rate: 0.003784 # Optimized from 0.01 → 0.003784
  weight_decay: 0.000135 # Optimized from 0.0001 → 0.000135

  # Early stopping for production
  patience: 8 # More patience for optimized model

# 🎯 Optuna Optimization Configuration
optimization:
  n_trials: 20 # Reduced for faster completion
  timeout: 3600 # 1 hour
  study_name: gaia_stellar_classification_v2
  direction: minimize # Minimize validation loss instead

  # MUCH less aggressive pruning - let more trials complete
  pruner:
    type: median
    n_startup_trials: 10 # Let 10 trials complete first
    n_warmup_steps: 5 # Wait 5 epochs before pruning

  # Hyperparameter search space - focused ranges
  search_space:
    learning_rate:
      type: loguniform
      low: 0.001
      high: 0.01 # More conservative range

    hidden_dim:
      type: categorical
      choices: [128, 256, 384] # Skip tiny 64, focus on good sizes

    dropout:
      type: uniform
      low: 0.1
      high: 0.3 # Wider range

    weight_decay:
      type: loguniform
      low: 0.00001
      high: 0.001

    num_layers:
      type: categorical
      choices: [2, 3, 4] # Add num_layers optimization

mlflow:
  tracking_uri: ./mlruns
  experiment_name: gaia_optuna_optimization
  experiment_description: "Hyperparameter optimization for Gaia stellar classification"

  tags:
    survey: Gaia
    task: stellar_classification
    optimizer: optuna
    version: v1.0

callbacks:
  early_stopping:
    patience: 20
    min_delta: 0.001
    monitor: val_loss
    mode: min

  model_checkpoint:
    monitor: val_loss
    mode: min
    save_top_k: 1
    save_last: true

  learning_rate_monitor:
    logging_interval: epoch
