hpo:
  # Hyperparameter search space
  search_space:
    learning_rate:
      type: loguniform
      low: 1e-5
      high: 1e-2
    hidden_dim:
      type: choice
      values: [64, 128, 256, 512]
    num_layers:
      type: int
      low: 2
      high: 6
    dropout:
      type: uniform
      low: 0.0
      high: 0.5
    batch_size:
      type: choice
      values: [16, 32, 64, 128]
  
  # Optimization settings
  algorithm: optuna
  n_trials: 50
  timeout: 3600  # 1 hour
  direction: maximize
  metric: val_acc
  
  # Pruning
  pruner: median
  n_startup_trials: 5
  n_warmup_steps: 10
  
  # Resources
  n_jobs: 1
  gpu_per_trial: 1
